version: '3.9'

services:
  web:
    build: 
      context: frontend
    ports:
      - 3000:3000
    depends_on:
      - database
      - backend

  backend:
    build:
      context: backend
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      - MYSQL_DATABASE=shoppingCart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
 
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shoppingCart
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
      
volumes:
  db-data: