version: '3.9'

services:

  backend:
    build:
      context: backend
      target: dev-envs
    ports:
      - 8080:8080
    environment:
      - MYSQL_DATABASE=shoppingCart
    networks:
      - spring-mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - db-data:/var/lib/mysql/data
    networks:
      - spring-mysql
    environment:
      - MYSQL_DATABASE=shoppingCart
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
volumes:
  db-data:
networks:
  spring-mysql: